#!/bin/bash
if [ $# -eq 0 ]; then
	echo "Provide filename: bak [filename]"
	exit 1
fi

for filename in "$@"; do
	if [ ! -e "${filename}" ]; then
		echo -e "\033[0;31mError404: '$filename' not found\033[0m"
		continue
	fi

	backup_file="${filename}-$(date +%F).bak"

	version=2
	while [ -e "$backup_file" ]; do
		backup_file="${filename}-$(date +%F)_v${version}.bak"
		((version++))
	done

	cp -r "$filename" "$backup_file"

	if [ -e "${backup_file}" ]; then
		echo "Backup created: $backup_file"
	fi
done
