#!/bin/bash
if [ $# -eq 0 ]; then
	echo "Provide filename: bak [filename]"
	exit 1
fi

if [ ! -e "$1" ]; then
	echo "Error404: '$1' not found"
	exit 1
fi

filename="$1"
backup_file="${filename}-$(date +%F).bak"

version=2
while [ -e "$backup_file" ]; do
	backup_file="${filename}-$(date +%F)_v${version}.bak"
	((version++))
done

cp -r "$filename" "$backup_file"

if [ -e "${backup_file}" ]; then
	echo "Backup created: $backup_file"
fi
