#!/bin/bash
if [ $# -eq 0 ]; then
	echo "Provide filename: bak [filename]"
	exit 1
fi

if [ ! -f "$1" ]; then
	echo "Error: 404"
	exit 1
fi

filename="$1"
backup_name=$(echo "$filename"|sed 's/\.\([^.]*\)$/\1/')
backup_file="${backup_name}-$(date +%F).bak"

cp -r "$filename" "$backup_file"

echo "Backup created: $backup_file"
